# SPDX-FileCopyrightText: 2022 WebReady Projects <https://github.com/wr-projects/>
#
# SPDX-License-Identifier: MIT

version: 2

updates:

- package-ecosystem: github-actions
  directory: ".github/workflows"
  target-branch: "main"

  schedule:
    interval: daily
    timezone: "Europe/Paris"
    time: "00:00"

  labels:
    - "source:ğŸ’šgithub_actions"
    - "source:ğŸ¤–bot"

  commit-message:
    prefix: "â¬†ï¸upgrade(ci)"

  reviewers:
    - "wr-projects/devops"
